[env]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
  jgromes/RadioLib @ ^6.4.0
  h2zero/NimBLE-Arduino @ ^1.4.0
  olikraus/U8g2 @ ^2.35.0
  bblanchon/ArduinoJson @ ^7.0.0

build_flags =
  -DARDUINO_USB_MODE=1
  -Ilib/codec2
  -DARDUINO_LOOP_STACK_SIZE=16384
  ; -DNDEBUG  ; раскомментировать для release (отключает Serial логи)

[env:heltec_wifi_lora_32_V3]
build_flags =
  ${env.build_flags}
  -DARDUINO_USB_CDC_ON_BOOT=0

[env:heltec_wifi_lora_32_V4]
build_flags =
  ${env.build_flags}
  -DBOARD_V4=1
  -DARDUINO_USB_CDC_ON_BOOT=1
